grid_map_topic: /grid_map_simple_demo/grid_map
grid_map_visualizations:
  - name: terrain_points
    type: point_cloud
    params:
     layer: terrain
    name: agent_points
    type: point_cloud
    params:
     layer: squirrel
  - name: terrain_grid
    type: occupancy_grid
    params:
     layer: terrain
     data_min: 0.08
     data_max: 1
